# Netlify Configuration for Next.js

[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

# Next.js plugin to handle SSR, API routes, etc.
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Client-side routing fallback (if plugin is removed or you're serving static output only)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
